baseURL: "https://relivnd.dev/"
languageCode: "en-us"
title: "relivnd"
theme: "hugo-PaperMod"
params:
  profileMode:
    enabled: true
    title: "Hi There!" # optional default will be site title
    subtitle: "I'm Tobi, a Cloud Consultant / Technical Sales Engineer / DevOps evangelist / Cloud Computing advocate from Switzerland. Currently I work @ copebit AG"
    # imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Blog
        url: "/posts"
      - name: About Me
        url: "/aboutme"
      - name: Tools
        url: "/tools"
      - name: Talks
        url: "/talks"
      - name: copebit AG
        url: "https://www.copebit.ch/en/home/"

  socialIcons: # optional
    - name: "linkedin"
      url: "https://www.linkedin.com/in/relivnd/"
    - name: "github"
      url: "https://github.com/relivnd"
    - name: "dev"
      url: "https://dev.to/relivnd"
    - name: "mastodon"
      url: "https://mastodon.social/@relivnd"
    - name: "email"
      url: "mailto:hej@relivnd.dev"

  ShowShareButtons: true
  ShareButtons: ["linkedin"] # To customize which share buttons to be enabled on page

  ShowReadingTime: true
  ShowBreadCrumbs: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
